services:
  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 127.0.0.1:8080:8080

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    restart: always
    ports:
      - 127.0.0.1:8081:80
    profiles:
      - production

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      SECRET_KEY: ${SECRET_KEY}

      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432

      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}

    restart: always
    depends_on:
      - db
    profiles:
      - production

volumes:
  pgdata: