services:
  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_DB: ujad_db
      POSTGRES_PASSWORD: abc@123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata: