# Generated by Django 5.1.7 on 2025-03-19 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_user_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_auth.user'),
        ),
    ]
