# Generated by Django 5.1.7 on 2025-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_authcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('consumer', 'consumer'), ('dispatcher', 'dispatcher')], default='consumer', max_length=50),
        ),
    ]
