# Generated by Django 5.1.7 on 2025-03-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_authcode_user'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrder',
            new_name='Ticket',
        ),
    ]
