# Generated by Django 5.1.7 on 2025-03-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productticket',
            name='product_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
