# Generated by Django 5.1.7 on 2025-11-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order_description_order_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('pending', 'pending'), ('canceled', 'canceled'), ('confirmed', 'confirmed')], default='created', max_length=50),
        ),
    ]
