# Generated by Django 5.1.7 on 2025-11-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='sales_order_created_8a4d37_idx'),
        ),
    ]
